Updating references to the new kie-ci actions folder.
kiegroup/kie-jpmml-integration pull request #77
Opened 2023-04-24 09:20 UTC by bacciotti

2023-05-18 08:50 UTC, Ginxo requested changes
please check

2023-05-18 08:50 UTC, Ginxo commented on .github/workflows/pull_request.yml
> +          definition-file: https://raw.githubusercontent.com/${GROUP:kiegroup}/droolsjbpm-build-bootstrap/${BRANCH:main}/.ci/pull-request-config.yaml
duplicated line, right? :thinking: 
```suggestion
```

2023-05-23 12:20 UTC, Ginxo approved these changes
LGTM

2023-05-23 12:30 UTC, lampajr approved these changes

2023-05-31 08:29 UTC, merged